In [3]:
import numpy as np

def lu_decomposition_crount(A):

    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.eye(n)  # Matriz U com 1s na diagonal principal

    # Verifica se a matriz é singular
    if np.linalg.det(A) == 0:
        raise ValueError("A matriz fornecida é singular e não pode ser decomposta.")

    for i in range(n):
        # Calcula os elementos de L
        for j in range(i, n):
            L[j, i] = A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))

        # Verifica se o elemento da diagonal principal de L é zero
        if L[i, i] == 0:
            raise ValueError(f"Zero encontrado na diagonal principal em L[{i}, {i}]. Pivotamento é necessário.")

        # Calcula os elementos de U
        for j in range(i + 1, n):
            U[i, j] = (A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))) / L[i, i]

    return L, U

def forward_substitution(L, b):

    #Resolve o sistema L * y = b usando substituição direta.

    n = L.shape[0]
    y = np.zeros(n)
    for i in range(n):
        y[i] = (b[i] - sum(L[i, j] * y[j] for j in range(i))) / L[i, i]
    return y

def backward_substitution(U, y):

   #Resolve o sistema U * x = y usando substituição reversa.


    n = U.shape[0]
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = y[i] - sum(U[i, j] * x[j] for j in range(i + 1, n))
    return x

def solve_linear_system(A, b):

    #Resolve o sistema linear Ax = b utilizando a decomposição LU pelo método de Crout.

    L, U = lu_decomposition_crount(A)
    print("Matriz L:")
    print(L)
    print("Matriz U:")
    print(U)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

def generate_matrix_and_vector():

    #Gera a matriz A (n x n) e o vetor b (n x 1) com entrada do usuário.

    n = int(input("Digite a ordem da matriz A: "))
    print("Digite os elementos da matriz A (linha por linha):")
    A = np.zeros((n, n))
    for i in range(n):
        A[i] = [float(x) for x in input(f"Linha {i + 1}: ").split()]

    print("Digite os elementos do vetor b:")
    b = np.array([float(input(f"b[{i + 1}]: ")) for i in range(n)])

    return A, b

# Exemplo de uso
if __name__ == "__main__":
    # Gera a matriz A e o vetor b
    A, b = generate_matrix_and_vector()

    # Solução do sistema
    try:
        x = solve_linear_system(A, b)
        print("Solução do sistema Ax = b:", x)
    except ValueError as e:
        print(f"Erro: {e}")



Digite os elementos da matriz A (linha por linha):
Digite os elementos do vetor b:
Matriz L:
[[ 3.          0.          0.        ]
 [-1.          7.          0.        ]
 [ 0.          3.         -6.57142857]]
Matriz U:
[[ 1.          0.         -0.33333333]
 [ 0.          1.          0.52380952]
 [ 0.          0.          1.        ]]
Solução do sistema Ax = b: [ 0.31884058 -0.07246377  0.95652174]
