In [100]:
# método de Gauss-Jacobi

import numpy as np
import random

def gauss_jacobi(A, b, x0, tol, max_iter=100000): 
    n = len(b)
    x = x0.copy()
    x_new = np.zeros_like(x)

    for k in range(max_iter):
        for i in range(n):
            sigma = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - sigma) / A[i, i]

        if np.linalg.norm(x_new - x, ord=np.inf) < tol: # Método de parada com a norma do máximo
            return x_new, k + 1

        x = x_new.copy()

    raise ValueError("O método de Gauss-Jacobi não convergiu dentro do número máximo de iterações.")

def verificaZeroDiagonalPrincipal(A):
    for i in range(len(A)):
        if(A[i,i] == 0):
            return True
    
    return False

def verificarSeTodosIguaisEmB(b):
    contador = 0

    for i in range(len(b)):
        if(b[0] == b[i]):
            contador+=1

    if(contador == len(b)):
        return True
    
    return False

def verificarSeTemDiagonalDominante(A):
    tamanhoA = len(A)
    contaDominantes = 0
    
    for i in range(tamanhoA):
        soma = 0

        for j in range(tamanhoA):
            soma += A[i,j]

        soma -= A[i,i]

        # Compara o elemento da diagonal principal com todos os elementos da linha que ele pertence
        if(A[i,i] > soma): 
            contaDominantes += 1
    
    if(contaDominantes == tamanhoA):
        return True
    
    return False

def verificarSeRaizesValidas(A, b, raizes, tol):
    linhaValida = 0

    for i in range (len(A)):
        somaLinha = 0

        for j in range(len(A)):
            somaLinha += A[i,j] * raizes[j]

        
        # Resultado da aplicação das raízes aproximadas na matriz
        print("Resultado da linha", i, ":",somaLinha)
       
        # Estabelcee precisão de validação, obs: ela deve ser uma casa decimal menos precisa que a tolerância do método de parada da função de gauss_jacobi
        if(abs(somaLinha - b[i]) <= tol*100000): 
            linhaValida += 1

    if(linhaValida == len(b)):
        return True
    
    return False

import random

def gerarMatrizQuadradaComDiagonalDominante(ordem):
    matriz = []
    for i in range(ordem):
        linha = []
        soma_na_linha = 0
        for j in range(ordem):
            if i == j:
                linha.append(0) # Primeiramente adiciona 0 em todos os índices da diagonal principal
            else:
                numero_aleatorio = float(random.randint(0, 20))  # Gera números menores para facilitar a soma
                linha.append(numero_aleatorio)
                soma_na_linha += numero_aleatorio
        
        # Ajusta o elemento da diagonal principal para ser dominante
        linha[i] = float(soma_na_linha + random.randint(1, 10))  # Adiciona um valor maior que a soma dos outros elementos no índice da diagonal principal
        
        matriz.append(linha)
    return matriz

def geraVetorBAleatorio(ordem): 
    vetor = []
    
    for i in range(ordem): 
        vetor.append(random.randint(0, 100)) 
        
    return vetor

'''

Verificações

1° Deve analisar se a matriz tem diagonal dominante 
2° Se tiver zero na diagonal principal, não deve funcionar 
3° Se todos os valores de b forem iguais, não deve funcionar 
4° Se o determinante da matriz for 0, ele não deve funcionar 
5° Não pode ser SPI ou SI, mas já basta verificar se o determinante é 0 
6° Verifica se a solução é válida aplicando na matriz

'''
# Input:
ordem = 5
tol = 1e-8

print("Ordem da Matriz A: ", ordem, "\n")
print("Matriz A:\n")

# Gera e exibe a matriz quadrada
A = np.array(gerarMatrizQuadradaComDiagonalDominante(ordem), dtype=float)
for linha in A:
    print(linha)

print("\nVetor b:\n")
b = np.array(geraVetorBAleatorio(ordem), dtype=float)
print(b, "\n")

if(verificarSeTemDiagonalDominante(A)):
    print("A matriz posssui diagonal dominante.")
else:
    print("A matriz não tem diagnonal dominante, logo a resposta tem a possibilidade de não ser válida de acordo com o método de Gauss Jacobi.\n")

if(not verificaZeroDiagonalPrincipal(A)):
    if(not verificarSeTodosIguaisEmB(b)):
        if(np.linalg.det(A) != 0):

            x0 = np.zeros_like(b) # Vetor inicial x0 necessário para começar os cálculos
            solution, iterations = gauss_jacobi(A, b, x0, tol)

            print("Solução aproximada:", solution, "\n")
            print("\nA raízes são válidas? ", verificarSeRaizesValidas(A,b,solution, tol))

            print("Número de iterações:", iterations) # Quanto menor o epsilon, maior o número de iterações

        else:
            print("Não há solução para uma matriz com determinante zero.")
    else:
        print("Todos os números em b são iguais, tente outro vetor.")
else: 
    print("Há zero na diagonal principal, tente outra matriz A.")


Ordem da Matriz A:  5 

Matriz A:

[40.  5.  1. 17. 14.]
[11. 40.  2. 12. 10.]
[18. 19. 63.  5. 19.]
[19.  3. 20. 61. 11.]
[ 5. 17.  4. 11. 41.]

Vetor b:

[89. 14. 47. 86. 42.] 

A matriz posssui diagonal dominante.
Solução aproximada: [ 1.69020995 -0.54682716  0.11744281  0.72023338  0.84030912] 

Resultado da linha 0 : 89.00000033625949
Resultado da linha 1 : 14.000000322065883
Resultado da linha 2 : 47.00000055575569
Resultado da linha 3 : 86.00000049953883
Resultado da linha 4 : 42.00000033719327

A raízes são válidas?  True
Número de iterações: 183


### Teste cast vs não cast ###


#A = np.array([ [5, 1, 3], [1, 3, -2], [3, 1, 5] ], dtype=float) 
#b = np.array([ 9, 9, 8 ], dtype=float)
#A = np.array([ [10, 2, 1], [1, 1, 1], [2, 3, 10] ], dtype=float) 
#b = np.array([ 7, -8, 6 ], dtype=float)
#A = np.array([ [9, -2, 3, 2], [2, 8, -2, 3], [-3, 2, 11, -4], [-2, 3, 2, 10] ], dtype=float) 
#b = np.array([ 54.5, -14, 12.5, -21], dtype=float)
#A = np.array([ [9, -2, 3, 2], [2, 8, -2, 3], [-3, 2, 11, -4], [-2, 3, 2, 10] ], dtype=float) 
#b = np.array([ 5, 5, 3, 5], dtype=float)

# Matriz 1:

    A = 
    [15, 5, -5],
    [4, 10, 1],
    [2, -2, 8]

    b = 
    [30, 23, -10]


     Solução com cast:
    Solução aproximada: [ 0.99999976  1.99999977 -1.00000001]
    Número de iterações: 16

     Solução sem cast:
    Solução aproximada: [ 1  2 -1]
    Número de iterações: 4

# Matriz 2:

    A = 
    [10, 2, 1],
    [1, 5, 1],
    [2, 3, 10]

    b = 
    [7, -8, -6]

    # Solução com cast:
    Solução aproximada: [ 1.08053702 -1.75838912 -0.28859044]
Número de iterações: 16

    # Solução sem cast:
    Solução aproximada: [ 0 -1  0]
    Número de iterações: 2

## Teste de matriz com sistema possível

# Matriz 1 (erro da dízima)

A = np.array([ [2, -1, 3], [1, 3, -2], [3, 1, 1] ], dtype=float) 
b = np.array([ 9, 6, 8 ], dtype=float)

# Matriz 2 (erro da dízima)

A = np.array([ [1, 1, 1], [2, -1, 3], [-1, 2, 2] ], dtype=float) 
b = np.array([ 6, 10, 5 ], dtype=float)

# Matriz 3 

A = np.array([ [3, -1, 2], [2, 4, 1], [1, -2, -3] ], dtype=float) 
b = np.array([ 4, 7, -6 ], dtype=float)

### Teste de Matriz com determinante igual a zero ###

# Matriz 1

    [1, 2, 3], [4, 5, 6], [7, 8, 9]
    
# Matriz 2

    [2, 4, 6], [1, 2, 3], [3, 6, 9]

# Matriz 3

    [1, 0, -1], [2, 0, -2], [3, 0, -3]


### Teste de Matriz com sistema indeterminado

# Matriz 1

    A = np.array([ [1, 2, 3], [2, 4, 6], [3, 6, 9] ], dtype=float) 
    b = np.array([ 5, 10, 15 ], dtype=float)

# Matriz 2

    A = np.array([
        [1, -1, 2],
        [2, -2, 4],
        [3, -3, 6]
    ], dtype=float)

    b = np.array([
        0, 0, 0
    ], dtype=float)

# Matriz 3

    A = np.array([
        [1, 3, -2],
        [2, 6, -4],
        [-1, -3, 2]
    ], dtype=float)

    b = np.array([
        1, 2, -1
    ], dtype=float)



### Teste de Matrizes com sistema impossível

# Matriz 1

    A = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]
    ], dtype=float)

    b = np.array([
        5, 10, 6
    ], dtype=float)

# Matriz 2

    A = np.array([
    [2, 4, 6],
    [1, 2, 3],
    [3, 6, 9]
    ], dtype=float)

    b = np.array([
        5, 3, 8
    ], dtype=float)

# Matriz 3

    A = np.array([
        [1, 0, -1],
        [2, 0, -2],
        [1, 1, 1]
    ], dtype=float)

    b = np.array([
        3, 6, 4
    ], dtype=float)
