In [35]:
import numpy as np 

A = np.array(((1,-1),(1,-1.00001)))
A2 = np.array(((1, -1),(1, -0.99999)))

b = np.array((1, 0))

print("Questão a)\n")

x = np.linalg.solve(A, b)
det = np.linalg.det(A)
cond = np.linalg.cond(A)

x2 = np.linalg.solve(A2, b)
det2 = np.linalg.det(A2)
cond2 = np.linalg.cond(A2)

print(f"x = {x}")
print(f"determinante de x = {det}")
print(f"condicionamento de x = {cond}")

print("___________\n")

print(f"x2 = {x2}")
print(f"determinante de x2 = {det2}")
print(f"condicionamento de x2 = {cond2}")

print("\n\n\nQuestão b)\n")

def calccond(n):
    matriz_b = np.zeros((n, n), dtype=float)
    b = np.zeros((n, 1), dtype=float)
    b.fill(1)

    for i in range(n):
        for j in range(n):
            matriz_b[i][j] = round(1 / (i + 1 + j + 1 - 1), 5)
        #print(f"matriz b: {matriz_b[i]}")
        #print("\n")

    print(f"matriz b | com n = {n}: \n{matriz_b}")
    condb = np.linalg.cond(matriz_b)
    print(f"\ndeterminate matriz_b: {np.linalg.det(matriz_b)}")
    print(f"\nsolução matriz_b: {np.linalg.solve(matriz_b, b)}")
    print(f"\ncondicionamento matriz_b: {condb}")

for n in range(3, 11):
    calccond(n)
    print("\n---\n")

Questão a)

x = [100000.99999934  99999.99999934]
determinante de x = -1.000000000006551e-05
condicionamento de x = 400002.00000320596
___________

x2 = [ -99999.00000046 -100000.00000046]
determinante de x2 = 9.999999999954488e-06
condicionamento de x2 = 399998.0000145242



Questão b)

matriz b | com n = 3: 
[[1.      0.5     0.33333]
 [0.5     0.33333 0.25   ]
 [0.33333 0.25    0.2    ]]

determinate matriz_b: 0.0004625740629630027

solução matriz_b: [[  3.00408348]
 [-24.02077805]
 [ 30.01921684]]

condicionamento matriz_b: 524.5016824671253

---

matriz b | com n = 4: 
[[1.      0.5     0.33333 0.25   ]
 [0.5     0.33333 0.25    0.2    ]
 [0.33333 0.25    0.2     0.16667]
 [0.25    0.2     0.16667 0.14286]]

determinate matriz_b: 1.6111107939416026e-07

solução matriz_b: [[  -4.18144631]
 [  61.99506442]
 [-184.75618416]
 [ 143.07477184]]

condicionamento matriz_b: 15920.810942833312

---

matriz b | com n = 5: 
[[1.      0.5     0.33333 0.25    0.2    ]
 [0.5     0.33333 0.25    