In [ ]:
import numpy as np

def pegarDadosCsv():
    T = []

    # Coloca os dados do .csv na matriz T
    with open('pontosQ9.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')

        pulaLinha1 = True

        for row in spamreader:

            # Pula a linha que tem as letras 'x' e 'y'
            if pulaLinha1:
                pulaLinha1 = False
                continue

            result = row[0].split(',')
            T.append((float(result[0]), float(result[1])))

    return T

def interpolacaoNewton(T, value):

    # Extrai x e y das colunas de T
    T = np.array(T)  # Garante que T seja um array NumPy
    x = T[:, 0]
    y = T[:, 1]
    
    n = len(x)
    coef = np.zeros([n, n])
    coef[:, 0] = y  # A primeira coluna é o vetor y
    
    # Construção da tabela de diferenças divididas
    for j in range(1, n):
        for i in range(n - j):
            coef[i, j] = (coef[i + 1, j - 1] - coef[i, j - 1]) / (x[i + j] - x[i])
    
    # Avaliação do polinômio usando o método de Horner modificado
    result = coef[0, 0]
    product_term = 1.0
    for i in range(1, n):
        product_term *= (value - x[i - 1])
        result += coef[0, i] * product_term
    
    return result, coef[0, :]


# Exemplo de uso
T = pegarDadosCsv()
print("Pontos dados (x,y):",T)

value_to_evaluate = 5  # Ponto onde o polinômio será avaliado

result, coefficients = interpolacaoNewton(T, value_to_evaluate)

print(f"Polinômio avaliado no ponto {value_to_evaluate}: {result}")
print(f"Coeficientes do polinômio: {coefficients}")


# Exibe o gráfico
x=np.linspace(0,10,500)
plt.figure(figsize=(4, 4))
plt.plot(x,p(x), color='#FF4500', marker = '', linewidth=1.0)

pointsX = []
pointsY = []

for point in T:
    pointsX.append(point[0])
    pointsY.append(point[1])

plt.scatter(pointsX, pointsY)

plt.grid()
plt.show()


Pontos dados (x,y): [(-1.0, 4.0), (0.0, 1.0), (2.0, -1.0)]
Polinômio avaliado no ponto 5: 6.0
Coeficientes do polinômio: [ 4.         -3.          0.66666667]


In [17]:
## Newton Divided Difference Polynomial Interpolation Method

import numpy as np

x=np.array([-1,0,2],float)
y=np.array([4,1,-1],float)
n=len(x)
p=np.zeros([n,n+1])#creating a Tree table (n x n+1 array)
value =float(input("Enter the point at which you want to calculate the value of the polynomial: "))

# first two columns of the table are filled with x and y data points
for i in range(n):
    p[i,0]=x[i]
    p[i,1]=y[i]

## algorithm for tree table from column 2 two n+1
for i in range(2,n+1): #column
    for j in range(n+1-i):# defines row
        p[j,i]=(p[j+1,i-1]-p[j,i-1])/(x[j+i-1]-x[j])#Tree Table
        np.set_printoptions(suppress=True)## this suppress the scientific symbol(e) and returns values in normal digits

# print(p) ## can check the complete Tree table here for NDDP
b=p[0][1:]#This vector contains the unknown coefficients in the polynomial which are the top elements of each column.
print("b= ",b)
print("x= ",x)
lst=[] # list where we will append the values of prouct terms

t=1
for i in range(len(x)):
    t*=(value-x[i]) ##(x-x0), (x-x0)(x-x1), (x-x0)(x-x1)(x-x2) etc..
    lst.append(t)
print("The list of product elements ",lst,end = ' ')
## creating a general function

f=b[0]

for k in range(1,len(b)):
    f+=b[k]*lst[k-1] ## important**[k-1]** not k because in list we use one step earlier element. For example for b1 we have to use (x-x0), for b2, we use (x-x0)(x-x1) for b3 we use (x-x0)(x-x1)(x2)

print("The value of polynomial: ","%.3f"%f)

 

b=  [ 4.         -3.          0.66666667]
x=  [-1.  0.  2.]
The list of product elements  [np.float64(6.0), np.float64(30.0), np.float64(90.0)] The value of polynomial:  6.000


In [ ]:
import numpy as np

def pegarDadosCsv():
    T = []

    # Coloca os dados do .csv na matriz T
    with open('pontosQ9.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')

        pulaLinha1 = True

        for row in spamreader:

            # Pula a linha que tem as letras 'x' e 'y'
            if pulaLinha1:
                pulaLinha1 = False
                continue

            result = row[0].split(',')
            T.append((float(result[0]), float(result[1])))

    return T

def interpolacaoNewton(mT):
    
    mT[0][2] = (mT[1][1] - mT[0][1]) / (mT[1][0] - mT[0][0])  
    print(mT, "\n")
    mT[1][2] = (mT[2][1] - mT[1][1]) / (mT[2][0] - mT[1][0])  
    print(mT, "\n")
    mT[0][3] = (mT[1][2] - mT[0][2]) / (mT[2][0] - mT[0][0])  
    print(mT, "\n")

    for i in range(2,n+1): #column
        for j in range(n+1-i):# defines row
            p[j,i]=(p[j+1,i-1]-p[j,i-1])/(x[j+i-1]-x[j])#Tree Table

    return mT

# Extrai x e y das colunas de T
T = np.array(pegarDadosCsv())  
qntLinhasMatrizTriangular = len(T)
qntColunasMatrizTriangular = len(T)+1

matrizTriangular = np.zeros([qntLinhasMatrizTriangular,qntColunasMatrizTriangular])

for i in range(qntLinhasMatrizTriangular):
    matrizTriangular[i][0] = T[i][0]
    matrizTriangular[i][1] = T[i][1]

print(matrizTriangular, "\n")

interpolacaoNewton(matrizTriangular)

[[-1.  4.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 2. -1.  0.  0.]] 

[[-1.  4. -3.  0.]
 [ 0.  1.  0.  0.]
 [ 2. -1.  0.  0.]] 

[[-1.  4. -3.  0.]
 [ 0.  1. -1.  0.]
 [ 2. -1.  0.  0.]] 

[[-1.          4.         -3.          0.66666667]
 [ 0.          1.         -1.          0.        ]
 [ 2.         -1.          0.          0.        ]] 



array([[-1.        ,  4.        , -3.        ,  0.66666667],
       [ 0.        ,  1.        , -1.        ,  0.        ],
       [ 2.        , -1.        ,  0.        ,  0.        ]])