In [97]:
import numpy as np

def pegarDadosCsv():
    T = []

    # Coloca os dados do .csv na matriz T
    with open('pontosQ9.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')

        pulaLinha1 = True

        for row in spamreader:

            # Pula a linha que tem as letras 'x' e 'y'
            if pulaLinha1:
                pulaLinha1 = False
                continue

            result = row[0].split(',')
            T.append((float(result[0]), float(result[1])))

    return T

def interpolacaoNewton(mT, qntLinhasMatrizTriangular):

    for i in range(2,qntLinhasMatrizTriangular+1): 
        for j in range(qntLinhasMatrizTriangular+1-i):
            mT[j,i]=(mT[j+1,i-1]-mT[j,i-1])/(mT[j + (i - 1), 0]-mT[j][0])

    return mT

def multiplicaPolinomio(mT, contador, x):
    mult = 1

    for i in range(contador):
        mult *= (x - mT[i][0])

    return mult

def imprimirMultiplicaPolinomio(mT, contador, x):

    for i in range(contador):
         print("(x -", mT[i][0], ")", end=' ')

def imprimirPolinomio(matrizTriangular):
    print("\n", matrizTriangular[0][1], " + ", end=' ')
    
    contador = 1

    for i in range(2, (qntLinhasMatrizTriangular + 1)):
        print(matrizTriangular[0][i], end=' ')
        imprimirMultiplicaPolinomio(matrizTriangular, contador, x)

        if qntLinhasMatrizTriangular - 1 == contador:
            continue

        print("+", end=' ')
        contador += 1

# Extrai x e y das colunas de T
T = np.array(pegarDadosCsv())  
qntLinhasMatrizTriangular = len(T)
qntColunasMatrizTriangular = len(T)+1

matrizTriangular = np.zeros([qntLinhasMatrizTriangular,qntColunasMatrizTriangular])

# Preenche a primeira coluna da matriz triangular com X e a segunda coluna com Y
for i in range(qntLinhasMatrizTriangular):
    matrizTriangular[i][0] = T[i][0]
    matrizTriangular[i][1] = T[i][1]

print(matrizTriangular)
print("\n")

matrizTriangular = interpolacaoNewton(matrizTriangular, qntLinhasMatrizTriangular)

print("\n")
print(matrizTriangular)

imprimirPolinomio(matrizTriangular)

somatorio = 0
contador = 1

# Calcular um ponto qualquer no polinômio
ponto = 3

for i in range(2, (qntLinhasMatrizTriangular + 1)):
    somatorio += matrizTriangular[0][i] * multiplicaPolinomio(matrizTriangular, contador, x)
    contador += 1

valorInterpolado = matrizTriangular[0][1] + somatorio

print("\n\nValor interpolado no ponto ", ponto, " = ", valorInterpolado)

[[  1.  52.   0.   0.   0.   0.]
 [  2.   5.   0.   0.   0.   0.]
 [  4.  -5.   0.   0.   0.   0.]
 [  5. -40.   0.   0.   0.   0.]
 [  7.  10.   0.   0.   0.   0.]]




[[  1.  52. -47.  14.  -6.   2.]
 [  2.   5.  -5. -10.   6.   0.]
 [  4.  -5. -35.  20.   0.   0.]
 [  5. -40.  25.   0.   0.   0.]
 [  7.  10.   0.   0.   0.   0.]]

 52.0  +  -47.0 (x - 1.0 ) + 14.0 (x - 1.0 ) (x - 2.0 ) + -6.0 (x - 1.0 ) (x - 2.0 ) (x - 4.0 ) + 2.0 (x - 1.0 ) (x - 2.0 ) (x - 4.0 ) (x - 5.0 ) 

Valor interpolado no ponto  3  =  6.0



    Lógica para resolvar matriz triangular
    
    '''
    mT[0][2] = (mT[1][1] - mT[0][1]) / (mT[1][0] - mT[0][0])  
    print(mT, "\n")
    mT[1][2] = (mT[2][1] - mT[1][1]) / (mT[2][0] - mT[1][0])  
    print(mT, "\n")
    mT[0][3] = (mT[1][2] - mT[0][2]) / (mT[2][0] - mT[0][0])  
    print(mT, "\n")
    '''